version: '2.2'

services:
  web:
    image: azuracast_cli:latest
    build:
      context: ./util/docker/testing
    environment:
      LANG: en_US.UTF-8
      APPLICATION_ENV: "testing"
    volumes:
      - .:/var/azuracast/www
