name: Test Suite

on: [push, pull_request]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Run test suite
      run: |
        cp azuracast.sample.env azuracast.env
        cp docker-compose.sample.yml docker-compose.yml
        cp docker-compose.testing.yml docker-compose.override.yml
        chmod 777 tests/_output/
        docker-compose build web
        docker-compose run --user="azuracast" --rm web azuracast_install
        docker-compose run --user="azuracast" --rm web composer test

    - name: Echo test output directory
      if: failure()
      run: |
        cat tests/_output/*.html
